name: getx_amplify
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_flutter: ^1.0.0
  flutter:
    sdk: flutter
  go_router: ^6.5.5
  google_maps_flutter: ^2.3.1
  google_maps_flutter_android: ^2.1.10
  google_maps_flutter_platform_interface: ^2.2.1
  flutter_google_places_sdk: ^0.3.2+5

assets:
    - assets/
